services:
  - type: web
    name: screenreader-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr scrot xvfb || echo "System packages installation failed, continuing..."
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: PORT
        generateValue: true
